### ISSUE TITLE
`rdedup init` does not work

### ISSUE THREAD

**Issue by dead10ck** [dpc/rdedup#101]
```sh
[I] ~/redup-test ∫ rdedup -d . init                                                                                              [08:36:19] 

.
Enter new passphrase: 
Enter new passphrase again: 
Error: repo already exists: .
[I] ~/redup-test ∫ lss                                                                                                           [08:36:35] 
total 16K
drwxr-xr-x  2 dead10ck dead10ck 4.0K May 10 08:35 ./
drwxr-xr-x 94 dead10ck dead10ck  12K May 10 08:35 ../
[I] ~/redup-test ∫ rdedup -d (pwd) init                                                                                          [08:36:47] 

/home/dead10ck/redup-test
Enter new passphrase: 
Enter new passphrase again: 
Error: repo already exists: /home/dead10ck/redup-test
[I] ~/redup-test ∫ rdedup -d (pwd) ls                                                                                            [08:38:35] 

/home/dead10ck/redup-test
Error: No such file or directory (os error 2)
```

**Comment by dpc** [comment]
You have to give it a non-existing directory. `.` already exists.

**Comment by dead10ck** [comment]
Oh, I see. It doesn't seem obvious from the help or error messages that `init` requires a non-existent directory. That also seems like a strange requirement. Is there a technical reason it can't create a new repo inside an existing directory? It's also different from the workflow from other tools, like git.

**Comment by phillipCouto** [comment]
This is an easy fix, we can improve the error message.

**Comment by phillipCouto** [comment]
Would this be easier to understand?
```/some/dir already exists, repo dir must not exist```

**Comment by dpc** [comment]
About the workflow. `rdedup` is not like `git` in that it is not supposed to work "along" with your data. It expects an exclusive storage directory (or (soon to be implemented soon remote) location) for itself to manage, that is unrelated to from where you are running it. I guess it is feasible to check if a directory does not already contain config files, `chunk/`, `name/`, `index/` subdirs etc. but I don't think it gains us anything...

**Comment by phillipCouto** [comment]
I think we just need to make the error more descriptive so the user knows you can only initialize a directory that doesn't exist yet.

**Comment by dead10ck** [comment]
Yes, that seems better.

**Comment by dead10ck** [comment]
@dpc I see your point, though from my personal perspective as a new user, there's no reason making a new repo in an empty directory shouldn't work.

**Comment by dpc** [comment]
The code is simpler, maintaince is simpler, checks are simpler. Also what should we do if there directory exists and there are files in it? There will be mess.

We could potentially allow existing directory as long as it's empty. Would that be OK?

**Comment by dead10ck** [comment]
I'm just giving you my perspective as a user. You're free to do what you whatever you judge best for your project ☺️ (though your last suggestion seems like a simple enough solution.)
