### ISSUE TITLE
rdedup (from crates.io) prints dir path to stdout

### ISSUE THREAD

**Issue by equalsraf** [dpc/rdedup#102]
The following does not happen when using the tip of the master branch, but I installed rdedup from cargo and running commands prints the directory to stdout e.g.

```
$ echo "test" | rdedup -d /tmp/testbk/ store testcase

/tmp/testbk/
1 new chunks
58 new bytes
```

This also happens when calling `load`

```
$ rdedup -d /tmp/testbk/ load testcase               

/tmp/testbk/
Warning: Use `--add-newline` option if you generated repo with rdedup version <= 0.2
Enter passphrase to unlock: 
test
```

which prevents me from piping the ouput through rdup-up, etc

What got me confused here was that both versions report `2.0.0-0.1` with `rdedup -V`.  But the latest tag is v1.0.2 (as is also reported in crates.io).

I have not checked the code any deeper, but it seems that there is a bug in the version published in crates.io wihch is fixed in master, and the version in crates.io is reporting the wrong version. with `-V`.

**Comment by dpc** [comment]
So you've installed 1.0.2-0.1 from crates.io and it's broken?

**Comment by equalsraf** [comment]
Yes,

**Comment by dpc** [comment]
Thanks for reporting it. We'll yank it from crates.io. It's a silly bug, that makes the `rdedup` not work at all. We need to add some form of end-to-end test. It is planned, just there was no manpower to do it.

**Comment by phillipCouto** [comment]
I will see if I can patch this quickly as using 1.0.2 is incompatible with 2.0.0-0.1 repos.

**Comment by phillipCouto** [comment]
So realistically we just need to release a new version to crates.io.

**Comment by phillipCouto** [comment]
For documentation purposes I found the commit related to the release of 2.0.0-0.1 and pushed it as a tag.

**Comment by phillipCouto** [comment]
The commit that added the printing was c38bc114c263009e677c3dc8e6514c570ca5c8d1 and was removed in 5fead569a35b01ad332c13de88e30d2f3908260a. Again this is for documentation.

**Comment by dpc** [comment]
I guess we could publish `2.0.0-0.2` even right now. Also `-0.1` denotes that it's very early alpha version, so we don't have to be that cautious with backward compatibility and stuff. It's a shame that `cargo` is picking up the unstable version by default...

**Comment by phillipCouto** [comment]
We can release a new version once #106 and #107 land.

**Comment by phillipCouto** [comment]
This is fixed now with the new version released to crates.io.
