### ISSUE TITLE
Add Cargo.lock

### ISSUE THREAD

**Issue by tjikini** [dpc/rdedup#118]
Can you please add Cargo.lock to repo?

**Comment by dpc** [comment]
It makes sense for the repo, but what's the reason? Does anything breaks with newer version of dependencies?

**Comment by tjikini** [comment]
Cargo.lock is [required](https://github.com/NixOS/nixpkgs/blob/19d3cf81d3436a6600f261579b55b9132a6ca8fb/pkgs/build-support/rust/fetch-cargo-deps#L53) for Nix package, which I would like to make.

**Comment by dpc** [comment]
Done. Thanks for reporting it!
