### ISSUE TITLE
Change the repo format.

### ISSUE THREAD

**Issue by dpc** [dpc/rdedup#131]
This will break backward compatibility, and thus should be done in a next major version (3.0).

The current format is kind of lame, and not very efficient (especially if random access would be implemented ever). The biggest issue is separate, tiny index files.

New format could just keep all chunks in `./data`, and count the number of levels of indirections. A saved name would be just a final hash, and number of indirections to follow.

Also, it seems that a fixed header of a couple of bytes, before every chunk data, would improve debuggability. It could store compression, encryption information (so these could be even mixed within the same repo).

`names` should be `yml` files. Easier to upgrade, can contain things like hostname, timestamp etc.

**Comment by bachp** [comment]
@dpc Why do you like to use YAML instead of [CBOR](http://cbor.io/) or [ProtocolBuffers](https://github.com/google/protobuf)? I think they would be more compact at the cost of not being human readable.

**Comment by dpc** [comment]
I like human readable stuff - easy to inspect. A `name` file is ~40B of entropy, nothing to try to save on. For data chunks itself an encoding like CBOR would make sense, but right now I just dump the fixed-length data one after the other. Maybe I should consider using CBOR for rdedup v3, since I'm planing to break backward compatibility anyway.

**Comment by bachp** [comment]
Just wanted to make you aware of the options.

**Comment by dpc** [comment]
For now, I am going to ignore changing chunk file format. Everything else is completed.
