### ISSUE TITLE
Build problem on MacOSX

### ISSUE THREAD

**Issue by green-coder** [dpc/rdedup#136]
I have a problem building rdedup on MacOSX 10.12.6. `libsodium` is not installed. What is the right way to install it on this platform ?

I tried `brew install libsodium` but it does not helps.

Error message: 

```
error: failed to run custom build command for `libsodium-sys v0.0.14`
process didn't exit successfully: `/var/folders/gy/xv4hyr610sd3ft7c8x14hjfh0000gp/T/cargo-install.LicujVzFIV4B/release/build/libsodium-sys-a37975ed1a68241e/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"`: No such file or directory (os error 2)"', src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `rdedup v2.0.0`, intermediate artifacts can be found at `/var/folders/gy/xv4hyr610sd3ft7c8x14hjfh0000gp/T/cargo-install.LicujVzFIV4B`

Caused by:
  build failed
```

**Comment by dpc** [comment]
Yes, you need to have libsodium installed on your system. I'm not a Mac user so all was able to do is to google, and maybe this would work: http://macappstore.org/libsodium/

**Comment by green-coder** [comment]
I think I misread my error message, it was only complaining about `pkg-config` missing. I solved my problem by installing it: `brew install pkg-config`

Then I ran into this problem:

```
error: failed to run custom build command for `rust-lzma v0.2.1`
process didn't exit successfully: `/var/folders/gy/xv4hyr610sd3ft7c8x14hjfh0000gp/T/cargo-install.U20XcrhgQ2IX/release/build/rust-lzma-82e184e07eb6eadd/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Could not find liblzma using pkg-config', .cargo/registry/src/github.com-1ecc6299db9ec823/rust-lzma-0.2.1/build.rs:10:2
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

... which I solved using `brew install xz`


To summarize, to install `rdedup` on MacOSX you will need:

  1. To make sure that brew is installed and up-to-date (run `brew update` twice).
  2. To ensure those packages are installed: `brew install pkg-config libsodium xz`
