### ISSUE TITLE
Using sha256sum of the plain chunk leaks some information ("confirmation of a file attack" )

### ISSUE THREAD

**Issue by dpc** [dpc/rdedup#16]
While not being a primary concern, maybe something could be done about it too.

First of all: rdedup repo is not supposed to be stored publicly and should be considered secret information. The main attack thread is someone breaking into one of the systems, which already grants a great deal of information and other attack vectors.

**Comment by dpc** [comment]
If we could reuse a recipient public key, and seal everything using it + nonce derived from the data itself, then output would be deterministic, so we could use it's sha256 instead.

**Comment by dpc** [comment]
I don't think it's possible to fix this without some compilicated cryptographic schemes that are way above my knowledge.

As a naive(?) mitigation, I've increased the chunk sizes significantly. What's left is to explicity document this "weakness" and then this issue can be closed.

**Comment by phillipCouto** [comment]
What about using a seed? This would prevent from dictionary attackes as all the hashes in the dictionary would need to be regenerated with the known seed which could make the attack more costly. Also since the use of the rolling checksum the dictionary would also need to be constructed with the same parameters as what rdedup uses to generate the digests. These 2 factors make dictionary attacks more expensive though not impossible. This is the only attack I can see that would be of concern.

The encryption protects from extracting data so even if they found a hash of a part of a file that may be of interest the attacker already has that data (they had the hash to find). The attacker would not be able to pull up the index which is encrypted that shows what names the chunk is a part of and in effect protect the sensitive data from exposure.

**Comment by dpc** [comment]
I'm not sure what do you mean. As I see it there's no way to completely solve this. If one wants to deduplicate chunks without unlocking the secret key, attacker can always just attempt to take a piece of data, store in the repo and see if it was already there or not. It's just fundamental to how rdedup is supposed to work.

Saying that, the size of the chunk is making the attacks more difficult (it seems to me: completely non-practical for recovery of anything secret), and the way rdedup is intended to be used, it should not be public. In case of a breach into system storing a copy of your bckups, the attacker might be able to tell if eg. certain file was possibly stored in the repo, but if your machine was compromised in the first place, you probably have bigger things to worry about.

**Comment by phillipCouto** [comment]
I guess what I am trying to figure out is what type of vulnerability are you exposed to if an attacker knows who have a chunk of data in your backup? The fact that they know you have that chunk means they have access to the data else where via different means. Is that really a security issue?

**Comment by dpc** [comment]
I don't fully understand. This issue is only about the ability of the attacker to check if a given piece of data is already stored in the repo. The attacker needs to know the data beforehand since brute-forcing is not really practical, I think.

Example: police being able to tell that you store a given movie file. The video file they use might have been recorded from p2p network you downloaded it, which gave them a warrant to check your computer, and then ability to confirm it is indeed in your rdedup repo.

**Comment by spikebike** [comment]
I believe that's called a confirmation attack.  Generally deduplication and confirmation attacks are at odd.  So if you illegally have a file, someone could confirm you have it.  If your secret manifesto gets out, an attacker could prove you have it.  If you backup a system, and attacker could figure out what OS your are using by watching the patch stream, and then watching for the presence of files contained in the update.

Although that last attack can happen even if you only leak data about the size of a file.

This kind of thing generally I think should be documented, and possibly allow users to tune between security and resistant to metadata leaking (type, contents, or size of files) and maximum duplication.

Personally I'd turn the dial towards maximum duplication, as long as the files were encrypted before upload.

**Comment by phillipCouto** [comment]
Very true with the configuration option in #36 this would be a step in the right direction to allow a user to mitigate this. It also depends on the country, as some countries require that data stored there encrypted must be decrypted by the owner by law when the data is seized.

**Comment by dpc** [comment]
So the tradeoffs is that the bigger the chunk, the harder it is to confirm anything is in the repo and the performance is better. The smaller the chunk, the better deduplication is when files change just by a tiny bit.
