### ISSUE TITLE
Doesn't build on ubuntu-16.04

### ISSUE THREAD

**Issue by spikebike** [dpc/rdedup#18]
$ sudo cargo install rdedup
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading rdedup v0.1.0
 Downloading flate2 v0.2.13
 Downloading rust-crypto v0.2.35
 Downloading winapi-build v0.1.1
 Downloading rand v0.3.14
 Downloading regex-syntax v0.3.1
 Downloading utf8-ranges v0.1.3
 Downloading log v0.3.6
 Downloading memchr v0.1.11
 Downloading pkg-config v0.3.8
 Downloading argparse v0.2.1
 Downloading rustc-serialize v0.3.19
 Downloading thread_local v0.2.5
 Downloading sodiumoxide v0.0.10
 Downloading libsodium-sys v0.0.10
 Downloading regex v0.1.69
 Downloading libc v0.2.11
 Downloading thread-id v2.0.0
 Downloading gcc v0.3.28
 Downloading kernel32-sys v0.2.2
 Downloading miniz-sys v0.1.7
 Downloading env_logger v0.3.3
 Downloading aho-corasick v0.5.2
 Downloading winapi v0.2.6
 Downloading rollsum v0.2.0
 Downloading time v0.1.35
 Downloading libc v0.1.12
 Downloading rdedup-lib v0.1.0
   Compiling pkg-config v0.3.8
   Compiling log v0.3.6
   Compiling regex-syntax v0.3.1
   Compiling gcc v0.3.28
   Compiling argparse v0.2.1
   Compiling libc v0.2.11
   Compiling miniz-sys v0.1.7
   Compiling winapi v0.2.6
   Compiling memchr v0.1.11
   Compiling rustc-serialize v0.3.19
   Compiling libc v0.1.12
.cargo/registry/src/github.com-88ac128001ac3a9a/libc-0.1.12/rust/src/liblibc/lib.rs:81:21: 81:39 warning: lint raw_pointer_derive has been removed: using derive with raw pointers is ok
.cargo/registry/src/github.com-88ac128001ac3a9a/libc-0.1.12/rust/src/liblibc/lib.rs:81 #![allow(bad_style, raw_pointer_derive)]
                                                                                                           ^~~~~~~~~~~~~~~~~~
   Compiling rollsum v0.2.0
   Compiling rust-crypto v0.2.35
   Compiling flate2 v0.2.13
   Compiling aho-corasick v0.5.2
   Compiling rand v0.3.14
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling thread-id v2.0.0
   Compiling time v0.1.35
   Compiling thread_local v0.2.5
   Compiling libsodium-sys v0.0.10
   Compiling utf8-ranges v0.1.3
   Compiling regex v0.1.69
   Compiling sodiumoxide v0.0.10
   Compiling env_logger v0.3.3
   Compiling rdedup-lib v0.1.0
   Compiling rdedup v0.1.0
.cargo/registry/src/github.com-88ac128001ac3a9a/rdedup-0.1.0/src/bin.rs:89:13: 89:29 error: imports are not allowed after non-item statements [E0154]
.cargo/registry/src/github.com-88ac128001ac3a9a/rdedup-0.1.0/src/bin.rs:89             use argparse::*;
                                                                                       ^~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/rdedup-0.1.0/src/bin.rs:89:13: 89:29 help: run `rustc --explain E0154` to see a detailed explanation

As instructed I reran with --verbose:
$ sudo cargo install --verbose  rdedup 
    Updating registry `https://github.com/rust-lang/crates.io-index`
       Fresh pkg-config v0.3.8
       Fresh log v0.3.6
       Fresh libc v0.2.11
       Fresh regex-syntax v0.3.1
       Fresh rustc-serialize v0.3.19
       Fresh libc v0.1.12
       Fresh gcc v0.3.28
       Fresh rand v0.3.14
       Fresh winapi v0.2.6
       Fresh winapi-build v0.1.1
       Fresh memchr v0.1.11
       Fresh aho-corasick v0.5.2
       Fresh utf8-ranges v0.1.3
       Fresh rollsum v0.2.0
       Fresh argparse v0.2.1
       Fresh kernel32-sys v0.2.2
       Fresh miniz-sys v0.1.7
       Fresh libsodium-sys v0.0.10
       Fresh thread-id v2.0.0
       Fresh time v0.1.35
       Fresh flate2 v0.2.13
       Fresh sodiumoxide v0.0.10
       Fresh thread_local v0.2.5
       Fresh rust-crypto v0.2.35
       Fresh regex v0.1.69
       Fresh rdedup-lib v0.1.0
       Fresh env_logger v0.3.3
   Compiling rdedup v0.1.0
     Running `rustc .cargo/registry/src/github.com-88ac128001ac3a9a/rdedup-0.1.0/src/bin.rs --crate-name rdedup --crate-type bin -C opt-level=3 --out-dir /home/bill/target-install/release --emit=dep-info,link -L dependency=/home/bill/target-install/release -L dependency=/home/bill/target-install/release/deps --extern rustc_serialize=/home/bill/target-install/release/deps/librustc_serialize-d9e72695d437325f.rlib --extern log=/home/bill/target-install/release/deps/liblog-30a8a27ec161f1be.rlib --extern rdedup_lib=/home/bill/target-install/release/deps/librdedup_lib-5adcfb581909a471.rlib --extern argparse=/home/bill/target-install/release/deps/libargparse-6266299da68ee07e.rlib --extern env_logger=/home/bill/target-install/release/deps/libenv_logger-6ddad1820b981994.rlib -L native=/usr/local/lib -L native=/home/bill/target-install/release/build/miniz-sys-d03126dbc9ee0074/out -L native=/home/bill/target-install/release/build/rust-crypto-6acb19580f9fa57f/out`
.cargo/registry/src/github.com-88ac128001ac3a9a/rdedup-0.1.0/src/bin.rs:89:13: 89:29 error: imports are not allowed after non-item statements [E0154]
.cargo/registry/src/github.com-88ac128001ac3a9a/rdedup-0.1.0/src/bin.rs:89             use argparse::*;
                                                                                       ^~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/rdedup-0.1.0/src/bin.rs:89:13: 89:29 help: run `rustc --explain E0154` to see a detailed explanation
error: aborting due to previous error
failed to compile `rdedup v0.1.0`, intermediate artifacts can be found at `/home/bill

**Comment by dpc** [comment]
Hi. What was the method of installation of rust compiler and cargo? What's the `rustc --version` and `cargo --version`.

**Comment by spikebike** [comment]
$ cargo --version
cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)

**Comment by dpc** [comment]
Oh. This rustc version is probably too old to compile one of dependencies. There's not much I can do about it. I recommend uninstalling and using rustup.rs instead. :)
