### ISSUE TITLE
Missing documentation on rdedup-lib

### ISSUE THREAD

**Issue by azzamsa** [dpc/rdedup#201]
Hi.

I see the latest version of rdedup-lib doesn't have a [documentation](https://docs.rs/crate/rdedup-lib/3.1.0).
I plan to use rdedup as a library, would you like to point me the starting point?. Something like [trust-dns client](https://github.com/bluejekyll/trust-dns/tree/main/crates/client). Where it contains the MWE and the docs.

Thank you for rdedup.

**Comment by dpc** [comment]
I'm afraid the code of the binary might might the best documentation how to use the library. :shrug:
