### ISSUE TITLE
Chunks files are impractically small

### ISSUE THREAD

**Issue by mbq** [dpc/rdedup#22]
Chunk files made by rdedup are mostly few KB, which makes larger backups consist of tons of files. This leads to a substantial fs metadata overhead and influences syncing.

I think they should be stored collapsed in larger groups or via some KV library (leveldb?).

**Comment by dpc** [comment]
I actually increased the chunk size in the latest version (0.1.1), have you tried it already?

**Comment by dpc** [comment]
About the KV library - I want chunks to by synchronized on file level (using Dropbox/Syncthing). Would that work with leveldb?

**Comment by dpc** [comment]
Hmm... I might need to increase the chunk size even futher.

**Comment by mbq** [comment]
This was for v0.1.1.

KVs could be a batteries-included approach to re-pack small chunks into larger chunk files; for smart sync (rsync) it should be mostly the same.

Obviously enlarging chunks is even simpler, however there is a question how would this impact deduplication... Maybe it should be left as a parameter?

**Comment by dpc** [comment]
Identified to be #23
