### ISSUE TITLE
This is project still active?

### ISSUE THREAD

**Issue by phillipCouto** [dpc/rdedup#25]

**Comment by dpc** [comment]
The status of it is: it's working well for me personally. I accept patches but don't actively add anything new myself.

**Comment by phillipCouto** [comment]
Ah ok but you are open to receiving contributions to the project as I may have a few to make it more efficient and reliable from my experience on my macbook.

**Comment by dpc** [comment]
Yes. I'd be very happy to help and merge PRs that improve it. Feel free to ping me on gitter if you have any questions.

I've updated README to be more clear about the current status.

**Comment by phillipCouto** [comment]
Perfect thank you!

I think it is a great tool and would like to help it along anyway I can.

**Comment by dpc** [comment]
Seems like you have interest in rdedup and I'm looking for people to share the ownership of it. As an appreciation of already done work and interest, and encouragement for future one, I've sent you a collaborator invite. You should have a push and review, PR merging rights and so on. I've set master to be protected (so everything needs to go through PRs).
