### ISSUE TITLE
Reducing Size of Channels

### ISSUE THREAD

**Issue by phillipCouto** [dpc/rdedup#26]
Are you opposed to reducing the size of the channels? 

The issue I am having is I am using rdedup to backup Virtual Machines and when channels are full because my mac is faster then the HDD I am storing the backup on I am using between 600-800MB of memory. After adjusting the code to see what may be causing the large memory usage tweaking the channels down to 16 and reducing the buffer size to 4K for various buffered operations lead to a huge reduction in memory consumption. 

Currently reduced the memory consumption to 40-60MB. As for backup performance I did not notice an impact as reviewing the call stack rdedup is waiting on FS operations like stat, rename, open most of time.

**Comment by dpc** [comment]
👍 . I guess it's #15 related.

**Comment by phillipCouto** [comment]
Closed #29
