### ISSUE TITLE
Provide more information / statistics

### ISSUE THREAD

**Issue by phillipCouto** [dpc/rdedup#31]
I think it would be beneficial to get more statistics out of the rdedup utility. Either as stdout or hidden behind the logging implementation with info!.

A few examples are:
- Number of chunks written / referenced and bytes consumed when storing
- Number of chunks / bytes freed when garbage collecting
- Number of bytes referenced when using du

What do you think?

**Comment by dpc** [comment]
Good idea. 

`info!` should be kept for debugging. I guess all these stats could be added to  `Repo` and be referenced as `Arc<Stats>` in `ReadContext` and other data structures that actually do things. I think it could all fit quite nicely with the existing code.

Then `Repo` would get methods to read these stats, and eg. API to zero-them-out. These a `rdedup-lib` user can do `Repo::open` do any operations, read counter, zero them, do another operation and so on.
