### ISSUE TITLE
Add some documentation for Contributing

### ISSUE THREAD

**Issue by phillipCouto** [dpc/rdedup#33]
Since there will be two of us and in the event anyone else would like to contribute we should create a contributing guideline either in the README.md or a separate document so everyone is on the same page for the process of contributing to rdedup.

**Comment by dpc** [comment]
Sure. Though I wouldn't worry too much about it yet. IIRC since I published `rdedup` there were handful small fixes PRs, one developer that was doing something similar, but a bit different, and you. So it's not exactly a crowded place. :)

**Comment by phillipCouto** [comment]
Ok so I will close this for now then and we can open again when we feel it is needed.
