### ISSUE TITLE
Define the Goals or Core Values of rdedup

### ISSUE THREAD

**Issue by phillipCouto** [dpc/rdedup#34]
To assist in guiding what contributions will be accepted for rdedup we should define the goals or core values of the project that must be maintained at all times. 

For example, consistency of data written to disk. 😄 

Probably best if it is is in the README front an center for everyone to see and referenced in the contributing guidelines.

**Comment by dpc** [comment]
So my goals were:

* be a backup system:
 * be reliable and durable 
 * handle decent amount of data in performant way
* make my personal usecase possible
 * use public key encryption to 
 * be file synchronization software like Dropbox/Syncthing friendly
* use Rust
* try to be as technically excellent as we can make it

I don't have any non-technical core values for rdedup. I don't believe Open Source should worry too much about politics. Civil behaviour, and sticking to technical merits are important.
