### ISSUE TITLE
add an example incremental backup script

### ISSUE THREAD

**Issue by legrostdg** [dpc/rdedup#38]
It would be great to have an example incremental backup script somewhere.

**Comment by dpc** [comment]
I don't understand. Every backup with rdedup is full and deduplicated. Incremental backups are unnecessary.

**Comment by legrostdg** [comment]
rdup manpage mentions incremental backups, I don't get how to do incremental backups with rdup + rdedup.

**Comment by dpc** [comment]
So `rdup` does have a concept of incremental backups. However with rdedup, one should always just do full backups.

Excerpt from my personal backup script:

```
echo "Backing up: $backup_file_path"

rdup $rdup_flags /dev/null "$src_path" \
	| rdedup --dir "$bck_dir" store "$name" \
	|| exit 1
```

**Comment by dpc** [comment]
`rdedup` will deduplicate all full backups together, so they will take only as much space as one full backup + all the changes between backups.

**Comment by legrostdg** [comment]
Maybe just adding an example backup script, for example with "$(date --iso-8601)" in the $name of the example you provided would be good to have somewhere (in doc/examples?). It would help to have some usable (complete) scripts for users :-).
