### ISSUE TITLE
Switch meta-configuration to more flexible file format

### ISSUE THREAD

**Issue by dpc** [dpc/rdedup#39]
Right now I just glued nonce, salt and so on to each other and dumped them in hex form to a file, with a "repo version" number first. But since rdedup is picking up functionality, a more extendable format will be better.

* pick format: JSON/TOML (see https://github.com/dpc/rdedup/issues/36#issuecomment-263960696)
* make rdedup-lib read old or new format
* make rdedup write a new format metadata
* add `rdedup-lib` call and `rdedup upgrade` command to upgrade rdedup repo

See #36 for previous discussion

**Comment by dpc** [comment]
I think I'm going to do it.

**Comment by phillipCouto** [comment]
Ok sweet =) I saw the WIP you have open.

**Comment by phillipCouto** [comment]
@dpc Is this considered complete now?

**Comment by dpc** [comment]
I guess. More fields can be added with time as needed.
