### ISSUE TITLE
Make chunk sizes configurable

### ISSUE THREAD

**Issue by dpc** [dpc/rdedup#40]
Pre-requirement: #39 

* Add a argument to `repo init` to use a chunk size different then a default one
* Add a field in repo meta-data to configure average chunk size

See #36 for previous discussion.

**Comment by phillipCouto** [comment]
Should this be adjustable in an existing repo?

**Comment by dpc** [comment]
The config should default to existing setting.

In the future there could be a migration path, but right now specifying it on `rdedup init` should be enough to start.

**Comment by phillipCouto** [comment]
@dpc Using the bitsize number should be fine right? We can example its meaning in project documentation.

**Comment by dpc** [comment]
I guess the command line should take something like 16K, 2M etc. and check if it's a power of 2, bigger than some minimum, etc. Internal representation in yml file can be just bitshift, yes.

Also, I think this should be coupled with chunking algorithm. In the `yml` file there should be a section `[chunking]` or something like that with `algorithm = bup` and `chunk_size_bits`. So in case there's ever different implementation of chunking, different `algorithm` can be used with completely different settings.

**Comment by phillipCouto** [comment]
Would this mean we would now have a v2 version of the config? Would this constitute a write_v2 method?

**Comment by dpc** [comment]
Not really. It should be backward compatible so no need to bump the version.

When `yml` file is serialized, and there's no `[chunking]` (or whatever is should be) then current default should be assumed.

On `changepassword` the `yml` is being re-written, then it can add the missing section then. But generally legacy repos should just work through defaults.
