### ISSUE TITLE
Limit size of the repo (quota-like support)

### ISSUE THREAD

**Issue by jpap** [dpc/rdedup#41]
I'd love to be able to effectively support a total-size restriction on the repo.

Initially I was thinking of just ordering my named backups by timestamp, and `rm && gc`'ing in chronological order until the size of the repo is within check.  But...

1. Would each successive `gc` run be slow on a large repo?
2. Would it then make sense to combine `gc` with a `rm` into some kind of new `prune` command?
3. Would it be feasible to rely on the timestamps of the named backups?

**Comment by dpc** [comment]
All of these is possible with a little bit of shell scripting. After every backup, run a `du -cks` on the repository, compare with quota, delete some of the last backups, do GC, check again.

It could also be added as a command to rdedup, or made into separate utlity, as `rdedup-lib` is reusable.

**Comment by jpap** [comment]
Understood; would each `gc` run be slower than baking in knowledge of the size of each named backup into the `gc` process itself? (Comment #2 above.)

**Comment by dpc** [comment]
Each backup is sharing data with all other backup, so I don't see a way to actually tell how much data will the actual deletion of a given named backup make. Also, the `gc` should be reasonably fast, especially after we improve it further (support for incremental gc and so on).

**Comment by phillipCouto** [comment]
The hard part is to strictly maintain the quota without going over you need to know the amount of new data coming in then figuring out how many names need to be deleted to make room for the new data. This can be a slippery slop as deleting a name may release chunks that can be reused by the new name coming in.

The only process that would be simple is create the new name then prune the names until the repo size is within the limit. We then have edge cases like what if one name is larger than the quota? What order do we process the names?

**Comment by jpap** [comment]
If we did one `gc` pass, could we collect statistics on the unique (non-shared) chunk-totals for each named backup, in chronological order, thereby knowing -- in one pass -- how far back to delete?

If that's possible, having this as a separate command to list {name, total size, unique size} would also be useful.

**Comment by phillipCouto** [comment]
@jpap du is the command for this I was thinking of extending it to display these statistics along side the full uncompressed size of the name.

**Comment by jpap** [comment]
> This can be a slippery slop as deleting a name may release chunks that can be reused by the new name coming in.

I'd be happy to avoid this problem; and just set a target size to prune an existing (possibly over-quota) repo.  I'd be doing this as a pre-step for syncing to a remote disk/cloud that has a finite quota limit.  My local storage may be more liberal.

> What order do we process the names?

By their filesystem timestamp.  Having a pluggable method (e.g. by {reverse}sort) would also be helpful.

**Comment by jpap** [comment]
> du is the command for this I was thinking of extending it to display these statistics along side the full uncompressed size of the name.

Yes; for what I am calling the "total size".  For the "unique size", i.e. the number of extra bytes relative to a set of base-name backups.  e.g. Assume you have backups B0, B1, B2, B3 in that order.  The "unique size" of B2 would be the size of chunks {B0, B1, B2} - {B0, B1}.

**Comment by dpc** [comment]
> What order do we process the names?

Currently `name/` files store just binary hash of the index file to use. They could be extended in similiar way to #39 , to include any additional metadata.

**Comment by jpap** [comment]
> Currently name/ files store just binary hash of the index file to use. They could be extended in similiar way to #39 , to include any additional metadata.

Yes; but each of these `name/[file]` have a timestamp of when they were created.  Personally I'd be naming these `YYYYMMDD-HHMMSS` and could easily sort based on that.

**Comment by dpc** [comment]
I personally do use a timestamp to name them. However it would much more reliable to let people name them as they please, and if any form of quota support would be included, to not rely on file-system timestamps that might get lost/changed during syncing between repos, or inside a claud backend.

**Comment by dpc** [comment]
I have implemented a new, improved GC that changes things a bit. I'm closing this one, since I can't see myself ever implementing it anyway. I would be happy to consider if someone was willing to do it.
