### ISSUE TITLE
`gc` command fails

### ISSUE THREAD

**Issue by jpap** [dpc/rdedup#42]
I'm getting a failure when trying to perform `gc`; stack trace below.  Any ideas?

```
$ RUST_BACKTRACE=1 rdedup -d repo gc
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 20, message: "Not a directory" } }', src/libcore/result.rs:799
stack backtrace:
   1:        0x100d86fe8 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:        0x100d89fbf - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:        0x100d89025 - std::panicking::default_hook::h0ac3811ec7cee78c
   4:        0x100d89636 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:        0x100d894d4 - std::panicking::begin_panic::h6ed03353807cf54d
   6:        0x100d893f2 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:        0x100d89357 - rust_begin_unwind
   8:        0x100daa7f0 - core::panicking::panic_fmt::h27224b181f9f037f
   9:        0x100d150c0 - core::result::unwrap_failed::hbbe45964de00535c
  10:        0x100d257d7 - rdedup_lib::Repo::list_stored_chunks::insert_all_digest::h42a864493005e8a7
  11:        0x100d2670d - rdedup_lib::Repo::gc::h2dfed9052416104b
  12:        0x100d0b11c - rdedup::main::hc2f849d74320671f
  13:        0x100d8a57a - __rust_maybe_catch_panic
  14:        0x100d88b66 - std::rt::lang_start::h538f8960e7644c80
```

**Comment by dpc** [comment]
Is this git, or released build?

**Comment by jpap** [comment]
Released; as installed with `cargo`:
```
$ rdedup -V
1.0.0
```

**Comment by dpc** [comment]
I think it was fixed in master. Are you able to compile manually and retry?

**Comment by phillipCouto** [comment]
Run with ```RUST_LOG=trace``` to see which file / folder it is failing at.

**Comment by jpap** [comment]
I unfortunately deleted the repo; after creating a new one, the `gc` command works (with 1.0.0).  Perhaps I had corrupted the repo earlier.  Closing unless I see it again.

**Comment by dpc** [comment]
I suspect this is an bug that was happening on OSX, when additional files were introduced by Finder when traversing the directory. @jpap is that what happened?

Anyway - @phillipCouto would you like to release a new version of rdedup? I've added you to the crates.io owners, so you can just bump the version of rdedup-lib, and `cargo publish`, then bump version of `rdedup` and dependency on `rdedup-lib` and `cargo publish`

**Comment by phillipCouto** [comment]
@dpc sure I can do it =)
