### ISSUE TITLE
Configurable chunks folder nesting (e.g. flat) for faster sync?

### ISSUE THREAD

**Issue by jpap** [dpc/rdedup#43]
Modern filesystems can have more than 64k files in them, as do many cloud storage systems.

Due to the two-level chunk folder organization, even a small backup can end up with a lot of folders.  Trying to sync a tree with about 1k folders to Google Drive (using rclone) takes forever because it has to issue a separate HTTP/API request for each folder to list the chunks for sync.

Can we have a configuration to select the nesting-level of the chunks folder?  It could default to two as current, but go down to zero where it's a single folder with all chunks contained.

**Comment by dpc** [comment]
I guess I'd be OK with it. It's similar to  #40 . Do you think you could submit a PR? If so you might want to sync with @phillipCouto about #39

**Comment by jpap** [comment]
I'm happy to work on this; no promises on when I'll have it ready as I'm unfortunately short on time.

**Comment by dpc** [comment]
:+1:

**Comment by phillipCouto** [comment]
I am gonna scoop this one up =)
