### ISSUE TITLE
Create Test Cases for rdedup command

### ISSUE THREAD

**Issue by phillipCouto** [dpc/rdedup#50]
As mentioned by @dpc in #49 we should have some form of tests to verify the rdedup command is performing the tasks as expected.

**Comment by dpc** [comment]
Example rust test that test behaviour of a binaries: https://github.com/slog-rs/envlogger/blob/master/tests/regexp_filter.rs

**Comment by dpc** [comment]
Done, now even as a matrix of features. Sits under `./scripts`
