### ISSUE TITLE
Rdedup as a log deduplication.

### ISSUE THREAD

**Issue by dpc** [dpc/rdedup#57]
So I'm also author of `slog-rs` and I'm thinking that when logging a lot of data, deduplication could be really useful (since logging tends to repeat the same information over and over again).

I'm thinking that I could write a `slog::Drain` (logging destination) that logs things to `rdedup` repo.

I think the following primitives would have to be added to `rdedup-lib`:

* `init_or_open` - open repo, create from scratch if not already there
* appending data - since `rdedup` treats data as a binary stream, it makes sense to be; should create a new `name` if not existing
* encryptionless mode - not every application requires encryption; logging in most cases does not, and the raw speed is actually more important;

**Comment by phillipCouto** [comment]
The only thing with the appending data is it will generate a lot of garbage as the old index chunks albeit small if being updated every second or so will accumulate over time and could make GC that more important.

**Comment by dpc** [comment]
Yes, appending will generate partial data chunks on edges. But it's supposed to happen very rarely. Usually logging is done by long running apps, that just continue streaming logs for hours or days. If an app like that gets restarted it can keep streaming to the previous, eg. daily name.

**Comment by phillipCouto** [comment]
Ah so it is in the rare event that the log is interrupted. Makes sense I think we need to have a comment though stating that excessive use can cause garbage to accumulate at a high rate.

**Comment by dpc** [comment]
After giving it some thought, it doesn't make much sense. Compression of logs will deduplicate enough.
