### ISSUE TITLE
Performance Difference between sync_all and sync_data

### ISSUE THREAD

**Issue by phillipCouto** [dpc/rdedup#66]
Version of nightly: ```rustc 1.16.0-nightly (c8af93f09 2017-01-18)```

Currently I was testing some code out and from curiosity I was wondering if we are seeing any gains from using sync_data over sync_all.

When I ran my tests I am noticing that using sync_all instead of sync_data results in rdedup using only 70% of the time used to store a bunch of git project data in an empty repo compared to the current version of rdedup

I am running rdedup from mac os 10.12.2 so it may be specific to mac os but I am going to test it on a linux machine I have and see if there is similar gains there.

The ironic thing is sync_data is supposedly more efficient if not the same as sync_all. Maybe from a simplicity point of view we should just use sync_all regardless.

**Comment by dpc** [comment]
What's the platform you're testing it on?

**Comment by phillipCouto** [comment]
```
active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.16.0-nightly (c8af93f09 2017-01-18)
```

**Comment by dpc** [comment]
You're results are very surprising. Do you have a way to test it on Linux as well?

**Comment by phillipCouto** [comment]
yeah I have a laptop that I can run my tests against to compare. I will do it before I leave work to see if it holds true for linux. Well it is a linux laptop running btrfs as the root filesystem. Which may demonstrate different results compared to an installation running ext4 as the root fs. Regardless I am going to explore this further.

**Comment by phillipCouto** [comment]
On Ubuntu 16.04 I didn't see any differences really between the two. Now it was a VM on my mac so tomorrow I will try it on the linux laptop I was referring to earlier.

**Comment by phillipCouto** [comment]
I am still not seeing a difference on the laptop. I have done it with the clone of the linux kernel as a good source of data size plus duplication as well as the clone of the rust source code when using slower devices.

**Comment by phillipCouto** [comment]
@dpc maybe you can give it a try on your machine to confirm what I am finding?

**Comment by dpc** [comment]
No difference here. I guess we should go with the full one, just to be on the reliable side.

**Comment by phillipCouto** [comment]
Yeah and it will probably be more consistent in terms of performance across platforms and filesystems.                                                                                                                                                                         Phillip Couto                                                                                                                                                                            From: notifications@github.comSent: January 22, 2017 1:04 PMTo: rdedup@noreply.github.comReply to: reply@reply.github.comCc: phillip@couto.in; author@noreply.github.comSubject: Re: [dpc/rdedup] Performance Difference between sync_all and sync_data (#66)  No difference here. I guess we should go with the full one, just to be on the reliable side.

**Comment by phillipCouto** [comment]
@dpc do you want to handle this minor adjustment in your rework of the storing pipeline?

**Comment by dpc** [comment]
Separate please. :) . Can you submit the PR? I'm actually not sure when I'll be able to find time to take care of it.
