### ISSUE TITLE
Linting of Code

### ISSUE THREAD

**Issue by phillipCouto** [dpc/rdedup#69]
I think it may be ideal to implement linting part of CI to keep the code in relatively good shape with best practices for rust. Just like we run rustfmt to keep the code formatted correctly.

I think clippy is the go to utility at the moment so we can break this item up into 2:
- [x] Fix all current linting warnings and errors found by clippy
- [x] integrate into CI for ongoing maintenance of the code.
- [x] Add rustfmt checking to make sure code is formatted before testing

@dpc what do you think?

**Comment by dpc** [comment]
Good idea. Especially the travis checking rustfmt + clippy.

**Comment by phillipCouto** [comment]
Completed by #70.
