### ISSUE TITLE
Make file a little excessive?

### ISSUE THREAD

**Issue by phillipCouto** [dpc/rdedup#71]
Isn't the make file a little excessive?

isn't ```cargo build``` and ```cargo test``` sufficient?

**Comment by phillipCouto** [comment]
@dpc Also I know I mentioned it in gitter but is the number of runs excessive? Maybe we can do a single run for the non release build as the code takes substantially longer to run.

**Comment by dpc** [comment]
In `Vim` I often use `:mak test` or `:mak somethingelse`. And that's for my convenience. I have a template that I just copy to every project. :D . Please don't remove it! :)

I'm not sure about the runs. Some bugs are random by nature, and running a lot of time helps expose them. Example: https://github.com/dpc/rdedup/blob/master/lib/src/lib.rs#L615
