### ISSUE TITLE
Scalable GC approach.

### ISSUE THREAD

**Issue by dpc** [dpc/rdedup#75]
It seems to me that current way of doing GC won't scale too well. With 128KiB chunks, each represented by 32 bytes hash, it requires building a hashmap that is only `128 * 1024 / 32 = 4096` smaller than the data itself (+ control structures). In case of repository of 1PiB, that's 256GiB index data and similar in-memory set to map against.

Also to build such in-memory index-set, one needs to go through all index data each time.

I see following angels of tacking that problem: persistence, reference counting, probabilistic datastructures.

Reference counting could be implemented such as each time a data chunk is  created, it would get a refcount = 1, and when another reference to it is written in index, the refcount is incremented.

Persistence would mean that the index-set does not have to be in memory and can be built, and updated on disk.

Probabilistic datastructures (like Bloom Filter) could be used as false positive matches are acceptable, and if I understand things right for eg. Bloom Filter 1% false positive rate can be reached by using just 10bits per element, which cuts the size of a index-set around 25 times (`32 * 8 bit / 10 bit = 25`).

The problems to consider are:
 
* atomicity of file operations (refcount increments, etc.)
* using in-place file modification is not very file synchronization friendly. Index-set could be however stored as host-local cache and therfore excluded from syncing. Each host would recreate it as needed.

**Comment by phillipCouto** [comment]
What goals are we trying to achieve with GC? I think we need to define the goals or guarantees first like accuracy and execution tome and then we can employ the correct technology to meet them. 

Also as per your example above I would argue to using larger bit sizes for the rolling sum when repositories reach such sizes because as you described the metadata alone for just the name of the chunks is hundreds of gigs in size which is massive for file system metadata storage.

**Comment by dpc** [comment]
> I would argue to using larger bit sizes for the rolling sum 

That only postpones the problem a bit by making it smaller by a given factor, not completely solves it. Which is a fair way to deal with it ATM.

**Comment by dpc** [comment]
https://github.com/gilbertchen/duplicacy/blob/master/DESIGN.md

**Comment by dpc** [comment]
Move to #132
