### ISSUE TITLE
Change config enum to use new serde feature.

### ISSUE THREAD

**Issue by dpc** [dpc/rdedup#79]
I wasn't super happy about the current format, and there it is:

https://serde.rs/enum-representations.html

**Comment by phillipCouto** [comment]
Ok but what do you want to change it to?

**Comment by dpc** [comment]
Right now things serialialize as externally tagged to:

```
encryption:
  encrytpionX:
    sec_key: sadfsadf
```

I want it to serialize to interanlly tagged on `type` key:

```
encryption:
  type: X
  sec_key: asdfasdf
```

There can be only one encryption, so it does not make sense to introduce additional level, and so on.

Serde just got support for that, so should be an easy fix, and we haven't released a version yet, so it's just the right time to do it.

**Comment by phillipCouto** [comment]
Ah ok now it makes sense :)

**Comment by dpc** [comment]
Fixed
