### ISSUE TITLE
Force maxium and minimum size of a chunk.

### ISSUE THREAD

**Issue by dpc** [dpc/rdedup#88]
Some pathological patterns (eg. `/dev/null`) can potentially never yield any chunk edges. Such cases could be devastating for memory consumption and so on. That's why I think there should be a limit to a chunk size. Eg. if no edge was found for `desired average size chunk * 16` the chunk edge is forced.

Onethe other side, too small chunks are undesirable as well: they leak too much information about the data via their sha256 hash, bloat the gc and file system. It should be OK to ignore chunk edges if the chunk would be smaller than eg. `128 bytes` or `desired average chunk size / 16`.

**Comment by phillipCouto** [comment]
You sure a factor of 16 times is ideal? Technically the chunk size max is 1GB so that could still result in a 16 GB chunk in memory.

Maybe the max can be like the minimum a factor plus a hard limit of 1GB?

**Comment by phillipCouto** [comment]
The chunk size max I am referring to is the maximum size that can be defined for a repo at init.

**Comment by dpc** [comment]
`16` is very arbitrary. But if someones wants 1GiB average chunks, I guess ... 16GiB maxium sounds about right...

**Comment by phillipCouto** [comment]
I guess what I was trying to say is should we have a combination of 16 times and a constant. The constant being the minimum and maximum values we defined for the command line parameter.

For the maximum it would be the lesser of 16 times ideal chunk size or 1GB.

For minimum it would be the greater of ideal chunk size divided by 16 or 1KB.

This way it is consistent with the rules we allow at the command line level?

**Comment by dpc** [comment]
Sounds reasonable.

**Comment by aidanhs** [comment]
Just a drive-by comment - bear in mind that even if you set a minimum chunk size, you need to roll over at least the last `WINDOW_SIZE` bytes of the minimum chunk size to be sure you've got the rollsum initialised with the right state.

**Comment by dpc** [comment]
Right.

**Comment by dpc** [comment]
`fastcdc` implements it, I have also added 64-byte minimum for all chunkers, to prevent hash collisions. Closing for now.
