### ISSUE TITLE
fadvise maybe?

### ISSUE THREAD

**Issue by dpc** [dpc/rdedup#89]
http://man7.org/linux/man-pages/man2/posix_fadvise.2.html

**Comment by phillipCouto** [comment]
My only issue with this is finding equivalent implementions in other OSs like windows.

**Comment by dpc** [comment]
We can just put it behing `cfg(...)` with NOP implementation for non-Linuxes.

**Comment by dpc** [comment]
If there's anything like that for other OSes, we can have it too of course. :)

**Comment by dpc** [comment]
https://github.com/jborg/attic/issues/252

**Comment by dpc** [comment]
Looks like more trouble than benefit, and it's mostly for input data, which is actually not even implemented in `rdedup` yet.
