### ISSUE TITLE
Improving chunker performance

### ISSUE THREAD

**Issue by dpc** [dpc/rdedup#92]

**Comment by dpc** [comment]
```
#!/bin/bash

env RELEASE=true make
rm -Rf testdir/chunk/*
dd if=1gbrand bs=1M count=512 | time ./target/release/rdedup -DD --dir testdir store 1gib
```

**Comment by dpc** [comment]
It looks to me I've implemented very lame chunker that `clone()`s a lot.

**Comment by dpc** [comment]
@aidanhs I was running some tests about the chunker performance. You've mentioned it possibly taking  3x the raw rollsum code. There might be some overhead there, however please note that for chunker `inside is both `input + inside` due to constrains in the code, and that chunker threads runs in parallel with multiple other threads, some cpu bounded as well.

**Comment by aidanhs** [comment]
> and that chunker thread runs in parallel with multiple other threads, some cpu bounded as well

This is a good point. So perhaps it'd be useful (in addition to rabin) to have a 'nopsum' that doesn't do any splitting at all and a 'stupidsum' that does it based on a very bad but fast condition so you can get a feel for theoretical max performance.

**Comment by dpc** [comment]
`gear`/`fastcdc` is very fast, and might be as good as we can get without getting into parallelisation. Closing.
