### ISSUE TITLE
Consider using sha2 crate instead of rust-crypto

### ISSUE THREAD

**Issue by newpavlov** [dpc/rdedup#94]
Migrating to it should be fairly straightforward. If you want I can create PR with the appropriate changes.

**Comment by dpc** [comment]
What exactly are the benefits? `rust-crypto` is not actively worked on? Is that all?

**Comment by newpavlov** [comment]
Mostly replacement of a large dependency by a much smaller one. Also `rust-crypto` is dependent on gcc, while `sha2` including all dependencies is a completely pure Rust. And of course maintainability means what in the future it could be optimized even further, e.g. after stabilization of simd. (of course not to the level of `ring`, but still)

**Comment by dpc** [comment]
Sounds good.

**Comment by dpc** [comment]
So, I'll get to it at some point, but if you have time, please submit a PR!

**Comment by newpavlov** [comment]
Another question: how about adding support for blake2? Maybe in the form of an additional feature? In case of RustCrypto `blake2b` is approximately four times faster compared to `Sha256`, on my machine it processes up to 750-760 MB/s.

**Comment by dpc** [comment]
There is a plan to make encryption, chunking and hashing algorithms configurable. The enums for algo and chunking are already there: https://github.com/dpc/rdedup/blob/c38bc114c263009e677c3dc8e6514c570ca5c8d1/lib/src/config.rs#L238

If you're interested you could add another enum for hashing, add command line options for `init`, and such PR would be very appreciated. I'd be happy to help answering any questions.

**Comment by dpc** [comment]
Having said that, at least on my setup the chunking algorithm is a bottlenecks ATM since it can't be easily paralized. But using faster hashing would definitely be an improvement and might make the chunking get more of CPU time.

**Comment by newpavlov** [comment]
As I mentioned in the PR, `RustCrypto/hashes` works through implementation of traits in the `digest` crate, so you can write you code generically over `Digest` trait, thus making it much easier to switch between hash functions.

Unfortunately, currently I will not be able to contribute to this, as I have to work on RustCrypto crates. But I think it's worth to create an issue for tracking this. How about writing to [forum](https://users.rust-lang.org/t/twir-call-for-participation/4821) about it?

I will close this issue as PR was accepted.

**Comment by dpc** [comment]
Thanks again! I have wrote a short post: https://users.rust-lang.org/t/twir-call-for-participation/4821/42?u=dpc
