### ISSUE TITLE
Error on OSX Sierra elp: message: proc_macro::__internal::with_parse_sess() called before set_parse_sess()!

### ISSUE THREAD

**Issue by symgryph** [dpc/rdedup#98]
error: proc-macro derive panicked
   --> /Users/thmunn/.cargo/registry/src/github.com-1ecc6299db9ec823/rdedup-lib-2.0.0-0.1/src/config.rs:223:21
    |
223 | #[derive(Serialize, Deserialize)]
    |                     ^^^^^^^^^^^
    |
    = help: message: proc_macro::__internal::with_parse_sess() called before set_parse_sess()!

error: Could not compile `rdedup-lib`.
Build failed, waiting for other jobs to finish...
error: failed to compile `rdedup v2.0.0-0.1`, intermediate artifacts can be found at `/var/folders/kc/x2zgsh5d7zl8m2p38l9f_0ph0000gn/T/cargo-install.BQBYysbyF6rf`

Caused by:
  build failed

**Comment by dpc** [comment]
Oh. No idea. That doesn't look like a problem with rdedup itself.

If you're using incremental compilation (`CARGO_INCREMENTAL=1`) try disabling it. If that doesn't help... let's ask on IRC.

**Comment by jpap** [comment]
I had the same issue on macOS -- are you using brew to install rustc?  It's a known issue; the solution is to [install from rustup](https://www.rust-lang.org/en-US/install.html).
